---
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - ./var/elasticsearch:/usr/share/elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    ports:
      - "127.0.0.1:5601:5601"
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
